## job specific set ups ##
job_name: anat-seg
exp_name: feat-anat-seg

device_generator:

task: feat-anat-seg
dataset_name: {'train': 'synth_id', 'test': 'synth_id_deform'}

eval_only: False 
debug: False 

resume: False
reset_epoch: False
resume_optim: True
ckp_path: 


lr_drops: [70,85]


batch_size: 1

mild_samples: 2
all_samples: 4
