## job specific set ups ##
job_name: adni-t1
exp_name: ft-bf
init_method: "tcp://localhost:9997"
 
device: #cuda:2
device_generator: #cuda:1

# ADNI     ADNI3     ADHD200       AIBL        HCP    OASIS3
#  T1     T1,FLAIR      T1     T1,T2,FLAIR    T1,T2     CT  
dataset: ADNI
modality: T1
train_subset: #0.05


#task: feat-bf
task: task-bf
dataset_name: {'train': 'supervised', 'test': 'synth_id_deform'}
task_f_maps: [64] 

eval_only: False 
debug: False 
freeze_feat: False


resume: False
resume_optim: True
reset_epoch: False
ckp_path: 
feat_ext_ckp_path: assets/brainid_pretrained.pth



lr_drops: [250,300]


batch_size: 1
 



## mild generator set up
mild_generator:   
  bf_scale_min: 0.02
  bf_scale_max: 0.04
  bf_std_min: 0.1
  bf_std_max: 0.6


log_itr: 100
vis_itr: 10000